version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
